
upstream fastcgi_backend {
server php:9000;
}
server {
server_name _;
listen 8080;
set $MAGE_ROOT /var/www/magento2;
set $MAGE_MODE developer; # or production
access_log /dev/stdout;
error_log /dev/stderr;
include /var/www/magento2/nginx.conf.sample;
}